From Johnny: January 10, 2012 12:18 PM These changes fixed the following error/PHP Notices
ERROR: Tue Jan 10 12:36:59 2012 [13462][1][FATAL] Executing repair query:  Query Failed: ALTER TABLE st_stfvldtn   add column    NULL ,add column    NULL ,  ADD  INDEX idx_name_del (name, deleted): MySQL error 1064: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near 'NULL ,add column    NULL ,  ADD  INDEX idx_name_del (name, deleted)' at line 1
---> the required field for event doesn't exist anymore in the edit view, make sure the detail view don't contain this field
---> \Custom_Resources\Activities_resources\Extension\modules\ST_StfVldtn\Ext\Vardefs\vardefs.php  (removed one field)
-------------------------------------------------------------------------------------------------------------------------
PHP NOTICE  (not serious)
[Tue Jan 10 13:11:57 2012] [error] [client 192.168.149.1] PHP Notice:  Undefined index: isDuplicate in /var/www/sugar/ncs_framework/ncs_controller.php on line 25, referer: http://192.168.149.128/sugar/index.php?module=PLT_Participant&action=DetailView&record=9bb88afa-157d-ec6f-8f4d-4f0c8ca29f8c
Fixed.
-------------------------------------------------------------------------------------------------------------------------
Change the langugae file for Notes
Custom_Resources\Activities_resources\SugarModules\modules\Notes\language\en_us.lang.php
-------------------------------------------------------------------------------------------------------------------------

Thanks,

Johnny